services:
  bot:
    image: bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./configs/config.yaml:/app/configs/config.yaml"
    restart: always
    command:
      - bot
      - -cfg
      - /app/configs/config.yaml
