bot:
  token: ""
  debug: true
  handle:
    - reply: "Привет 👋 \n\\-\\-\n _отправлено через бота @super\\_puper\\_stas\\_bot_"
      income_messages:
        - привет
        - hello
        - здарова
        - добрый день
        - добрый вечер
        - хай
        - прив
        - алло
        - приветствую
        - hi
        - хаю хай
        - здравия желаю
  ignore_messages_from:
    - 11